  
{{- $root := . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name  }}-ingress
  namespace: default
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - backend: 
              serviceName: {{ printf "%s-%s" $root.Release.Name .serviceName}}
              servicePort: {{ .servicePort }}
        {{- end }}
  {{- end }}
