apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vue
  labels:
    {{- include "simplads-chart.labels" . | nindent 4 }}-vue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simplads-chart.selectorLabels" . | nindent 6 }}-vue
  template:
    metadata:
      labels:
        {{- include "simplads-chart.selectorLabels" . | nindent 8 }}-vue
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "simplads-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.simplads_vue.repository }}:latest"
          imagePullPolicy: {{ .Values.image.simplads_vue.pullPolicy }}
          env:
          - name: VUE_APP_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: simplads-vue
                key: baseUrl
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
