apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vue
data:
  baseUrl: {{ printf "http://api.dapr.fun/v1.0/invoke/%s-api/method/" .Release.Name }}
  redirectUri: https://web.dapr.fun