kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: {{ .Release.Name }}-api
    heritage: {{ .Release.Name }}
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi