apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "simplads-chart.labels" . | nindent 4 }}-api
spec:
  type: {{ .Values.service.simplads_api.type }}
  ports:
    - port: {{ .Values.service.simplads_api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simplads-chart.selectorLabels" . | nindent 4 }}-api
