apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vue
  labels:
    {{- include "simplads-chart.labels" . | nindent 4 }}-vue
spec:
  type: {{ .Values.service.simplads_vue.type }}
  ports:
    - port: {{ .Values.service.simplads_vue.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simplads-chart.selectorLabels" . | nindent 4 }}-vue
