apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zipkin
  labels:
    {{- include "simplads-chart.labels" . | nindent 4 }}-zipkin
spec:
  type: {{ .Values.service.simplads_zipkin.type }}
  ports:
    - port: {{ .Values.service.simplads_zipkin.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simplads-chart.selectorLabels" . | nindent 4 }}-zipkin
