name: simplads-api

on:
  push:
  #  paths:
  #    - "simplads-api/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          git fetch --tags
          git branch --create-reflog master origin/master
      - name: Install GitVersion
        uses: gittools/actions/setup-gitversion@v0.3
        with:
          versionSpec: '5.1.3'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/execute-gitversion@v0.3        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: trumhemcut/simplads_api:${{ steps.gitversion.outputs.fullSemVer }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./simplads-api
